namespace EnvironmentAssessment.Common.VISoap
{
    public enum RecommendationReasonCode
	{
		fairnessCpuAvg,
		fairnessMemAvg,
		jointAffin,
		antiAffin,
		hostMaint,
		enterStandby,
		reservationCpu,
		reservationMem,
		powerOnVm,
		powerSaving,
		increaseCapacity,
		checkResource,
		unreservedCapacity,
		colocateCommunicatingVM,
		balanceNetworkBandwidthUsage,
		vmHostHardAffinity,
		vmHostSoftAffinity,
		increaseAllocation,
		balanceDatastoreSpaceUsage,
		balanceDatastoreIOLoad,
		balanceDatastoreIOPSReservation,
		datastoreMaint,
		virtualDiskJointAffin,
		virtualDiskAntiAffin,
		datastoreSpaceOutage,
		storagePlacement,
		iolbDisabledInternal,
		xvmotionPlacement,
		networkBandwidthReservation
	}
}
