//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentAssessment.Common.VISoap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnvironmentAssessment.Common.VISoap.R.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert object with type {0} to {1}..
        /// </summary>
        internal static string InvalidObjectType {
            get {
                return ResourceManager.GetString("InvalidObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property name: {0}..
        /// </summary>
        internal static string InvalidPropertiesParam {
            get {
                return ResourceManager.GetString("InvalidPropertiesParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path is invalid..
        /// </summary>
        internal static string InvalidPropertyPath {
            get {
                return ResourceManager.GetString("InvalidPropertyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceUrl is not set..
        /// </summary>
        internal static string InvalidServiceUrl {
            get {
                return ResourceManager.GetString("InvalidServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid managed object type: {0}..
        /// </summary>
        internal static string InvalidViewType {
            get {
                return ResourceManager.GetString("InvalidViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewType is not ManagedEntity..
        /// </summary>
        internal static string InvalidViewTypeParam {
            get {
                return ResourceManager.GetString("InvalidViewTypeParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not supported in API version {0}..
        /// </summary>
        internal static string MethodNotSupported {
            get {
                return ResourceManager.GetString("MethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path is not correct. Element &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string PropertyDoesNotExist {
            get {
                return ResourceManager.GetString("PropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceContent is not initialized..
        /// </summary>
        internal static string ServiceContentNotInitialized {
            get {
                return ResourceManager.GetString("ServiceContentNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMware session cookie is not initialized.Try to connect first..
        /// </summary>
        internal static string SessionCookieNotInitialized {
            get {
                return ResourceManager.GetString("SessionCookieNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId is not initialized..
        /// </summary>
        internal static string SessionIdNotInitialized {
            get {
                return ResourceManager.GetString("SessionIdNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not specify type for data objects:&apos;{0}&apos;.
        /// </summary>
        internal static string SpecifiedDataObjectType {
            get {
                return ResourceManager.GetString("SpecifiedDataObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vim web service is not initialized. Try to connect first..
        /// </summary>
        internal static string VimWebServiceNotInitialized {
            get {
                return ResourceManager.GetString("VimWebServiceNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; should be &apos;{1}&apos; or one of its inheritors..
        /// </summary>
        internal static string WrongPropertyType {
            get {
                return ResourceManager.GetString("WrongPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;*&apos; can only be at the end of the property path..
        /// </summary>
        internal static string WrongWildcardPosition {
            get {
                return ResourceManager.GetString("WrongWildcardPosition", resourceCulture);
            }
        }
    }
}
